name: Android CI

on:
  push:
    branches: [ main, ci/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept licenses & install SDK packages
        run: |
          yes | sdkmanager --licenses >/dev/null
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      # 关键：直接调用 Gradle Wrapper 主类，不依赖 ./gradlew 脚本
      - name: Build debug APK
        run: |
          java -Dorg.gradle.appname=gradlew \
               -classpath gradle/wrapper/gradle-wrapper.jar \
               org.gradle.wrapper.GradleWrapperMain \
               :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
