name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write   # 允许自动把生成的 wrapper 提交回仓库

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 用“外置 Gradle 8.9”先生成本仓库的 wrapper（你仓库里现在没有/不对）
      - name: Generate Gradle Wrapper (8.9)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9
      - name: Create wrapper files
        run: |
          gradle wrapper --gradle-version 8.9 --distribution-type all
          mkdir -p gradle/wrapper
          # 显式把 distributionUrl 改到 8.9-all，防止版本不对
          sed -i 's#distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-8.9-all.zip#' gradle/wrapper/gradle-wrapper.properties

      - name: Commit Wrapper
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci: add/update Gradle wrapper 8.9"
          file_pattern: |
            gradlew
            gradlew.bat
            gradle/wrapper/**

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Verify versions
        run: ./gradlew --version

      - name: Build Debug APK
        run: ./gradlew clean :app:assembleDebug --stacktrace --no-daemon --warning-mode all

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
