
name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 强制 IPv4，拉依赖别走蹦跶的 IPv6；顺便把超时拉长点
      GRADLE_OPTS: >-
        -Djava.net.preferIPv4Stack=true
        -Dorg.gradle.internal.http.connectionTimeout=60000
        -Dorg.gradle.internal.http.socketTimeout=180000
        -Dorg.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 用“安装版 Gradle 8.9”直接跑，不依赖 wrapper 下载分发包，避开 services.gradle.org
      - name: Use Gradle 8.9
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.9

      # 没有 wrapper 也无所谓；有的话顺手加可执行权限但不强求
      - name: Make wrapper executable (best-effort)
        run: chmod +x ./gradlew || true

      # 关键：用 `gradle` 命令构建（不是 ./gradlew），加重试避免偶发网络波动
      - name: Build Debug APK (retry x3)
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 25
          command: |
            gradle --version
            gradle clean :app:assembleDebug --stacktrace --no-daemon --warning-mode all

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
